### ISSUE TITLE
Plugin idea:  List suspicious Keyboard layouts 

### ISSUE THREAD

**Issue by nbareil** [airbus-cert/regrippy#6]
Verbatim copy of @Neo23x0's interesting [tweet](https://twitter.com/cyb3rops/status/1183650239246405632):

> Imagine that the keyboard layouts are stored in HKCU > NTUSER.dat located in the user's profile directory on DCs
>
> A tool that would parse the NTUSER.dats & map ↔️ the users ENV language settings to the keyboard layout preloads could generate a list of suspicious combinations 💡 https://twitter.com/cyb3rops/status/1183431685402234880

This should be implementable easily in regrippy!

**Comment by simsor** [comment]
Indeed! I'm working on it :)

Some documentation for anyone who might stumble on this issue later:

- Format of the `Keyboard Layout\{Preload,Substitutes}` registry keys: https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=Kbd_Registry
- On a Windows machine, `HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layouts` contains a bunch of keyboard layout information
